### GENERAL SETTINGS ###

# Site settings
title: "ANIMAX"
description: "Le lab du management"
analytics: "" #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://animax.management"

# Build settings
markdown: kramdown
permalink: /:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#000000" 
  primary_rgb: "30,30,30" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#ffffff" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/groups/1459614080942550/
  - title: twitter
    url: http://twitter.com/animax

    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Une adresse 
email: bonjour@animax.management
tel: +33 (0) 619 58 85 50


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Arthur Schmitt 
    position: Lead prototypage
    text: "Ingénieur (ENSAM, Imperial College) et designer (RCA), Arthur est passionné par les nouvelles technologies et les pratiques collaboratives. Installé depuis un an à Montréal, il a auparavant participé à l’émergence des fablabs en France, notamment en contribuant à l'ouverture du premier fablab dans le centre de Paris."
    img: arthur_carre.jpg
    social:
      - title: envelope #use for email address
        url: mailto:arthur@tinktank.org
      - title: twitter
        url: http://twitter.com/tart2000
  - name: Justine G. Chapleau
    position: Lead projets
    text: "Graduée de la maîtrise en Muséologie à l’UdeM et à l’UQÀM où elle s’est spécialisée dans la reconnaissance et le recensement des initiatives de hacking culturel en milieu muséal, Justine tente toujours de repousser les limites préétablies en réalisant des projets multidisciplinaires."
    img: justine_carre.jpg
    social:
      - title: envelope #use for email address
        url: mailto:justine@tinktank.org
      - title: twitter
        url: http://twitter.com/justineGChaplea
  - name: Lucie Brillouet 
    position: Lead design 
    text: "Diplômée en design industriel (BDI / UdeM) et graduée du DESS in Communication Studies (Concordia), sa soif de culture ne s’arrête pas là. Après avoir mis un pied dans l’organisation d’événement culturel grâce au festival Art Souterrain, Lucie souhaite accompagner l’émergence de nouvelles pratiques collaboratives au croisement de la culture, du design et des nouvelles technologies."
    img: lucie_carre.jpg
    social:
      - title: envelope #use for email address
        url: mailto:lucie@tinktank.org
      - title: twitter
        url: http://twitter.com/Lucie_Brllt

    
# Clients information. Shown on Home and About pages.
clients:
  - name: Visiativ
    img: visiativ.png
    link: http://www.visiativ.com/
  - name: ERASME
    img: erasme.png
    link: http://www.erasme.org/
  - name: valpre
    img: valpre.png
    link: http://www.valpre.com/
  - name: meetings
    img: meetings.png
    link: http://www.meetings.fr/
    
# Principes de travail 
principes:
  - name: Prototypage
    faicon: cubes
    texte: "Le prototype est au coeur de notre philosophie de travail et de nos projets. Il permet de tester rapidement des idées et de réunir une équipe autour d'un concept."
  - name: Collaboration 
    faicon: comments
    texte: "Notre passion : faire travailler les gens de manière collaborative. Pour cela, nous expérimentons en permanence avec les nouvelles pratiques et les nouveaux outils."
  - name: Ouverture
    faicon: unlock
    texte: "Nous pensons qu'à l'heure du numérique, l'innovation doit passer par l'ouverture et le partage. C'est pourquoi tous les projets que nous développons sont documentés et partagés."

# Questions 
questions: 
  - titre: "J'ai une idée de projet, est-ce que je peux vous en parler ?"
    reponse: "Oui !"
    n: 1
  - titre: "Travaillez-vous avec des entreprises ?"
    reponse: "Nous travaillons avec toutes les personnes / institutions / organisations qui portent les mêmes valeurs que nous, sans restrictions. Si c'est votre cas, n'hésitez pas à nous contacter pour en discuter."
    n: 2

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Animax : Le lab du management"
about_plus: "Le collectif Animax réunit une équipe de professionnels avec l'envie commune de vouloir insufler une nouvelle manière de faire du management."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
